name: rodin_essential_ui
description: Rodin Essential zero-DEX Flutter AOT interface.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true